config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'developers/new'

  root 'staticpages#home'

  get 'help'    => 'staticpages#help'
  get 'about'   => 'staticpages#about'
  get 'contact' => 'staticpages#contact'
  get 'signup'  => 'developers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :admins
  resources :developers
  resources :projects

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "storyboard", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <% if logged_in? %>
	<li><%= link_to "Settings", edit_developer_path(current_user) %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
	<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'default', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
     <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      </div>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>